//
// Symantec ResourceStudio generated header file
//
// This file is intended for use with Windows 95
//

#define IDD_DIALOG                                      100
#define IDD_DIALOG_SUBONE                               101
#define IDD_DIALOG_SUBTWO                               102
#define IDD_DIALOG_SUBTHREE                             103
#define IDC_OPTIONS                                     3001


